# Generated by Django 3.1.7 on 2021-03-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptQueryAudit',
            fields=[
                ('created', models.DateField(auto_created=True)),
                ('transaction_id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
